package com.ch.voxel;

import java.util.ArrayList;
import java.util.List;

import com.ch.Model;
import com.ch.SimplexNoise;
import com.ch.Util;
import com.ch.math.Matrix4f;

/**
 * is a Java class responsible for representing a chunk of a 3D grid in a Minecraft-like
 * game. It has several fields and methods to handle the chunk's vertices, indices,
 * and neighboring chunks. The `toGenModel` method generates a list of vertices and
 * indices for the chunk and stores them in instance variables, while the `genModel`
 * method creates a model from these data. The `createModel` method is used to load
 * the model into memory, and the `gen` method is used to generate the vertices and
 * indices for a given chunk.
 */
public class Chunk {

	public static final int CHUNK_SIZE = 64;
	private static final int CHUNK_SIZE_SQUARED = CHUNK_SIZE * CHUNK_SIZE;
	private static final int CHUNK_SIZE_CUBED = CHUNK_SIZE * CHUNK_SIZE * CHUNK_SIZE;

	private Block[] blocks;
	public int x, y, z;
	private Model model;
	
	/**
	 * retrieves a `Model` object and sets a flag to indicate if it was generated or not.
	 * 
	 * @returns a `Model` object.
	 * 
	 * 	- `to_gen_model`: This variable is set to `true` when the model is generated by
	 * the function and `false` otherwise.
	 * 	- `model`: The variable `model` returns the generated model instance. Its attributes
	 * can vary depending on the implementation.
	 */
	public Model getModel() {
		if (to_gen_model) {
			createModel();
			to_gen_model = false;
		}
		return model;
	}
	
	/**
	 * creates a matrix that represents the transformation from the world coordinates to
	 * the model coordinate system. The matrix is initialized with a translation vector,
	 * where x, y, and z represent the offset from the origin in each dimension.
	 * 
	 * @returns a 4x4 matrix representing the translation of a 3D model within a chunk.
	 * 
	 * The matrix returned is an instance of the `Matrix4f` class in Java, which represents
	 * a 4D vector space.
	 * 
	 * The matrix has been initialized with a translation component, where x, y, and z
	 * represent the offset from the origin in the x, y, and z directions, respectively.
	 * These values are multiplied by the chunk size, indicating that the translation is
	 * applied to each vertex in the chunk.
	 * 
	 * This function returns a new instance of `Matrix4f` instead of modifying the original
	 * matrix, which allows for efficient computation and prevention of unintended changes
	 * to the matrix.
	 */
	public Matrix4f getModelMatrix() {
		return new Matrix4f().initTranslation(x * CHUNK_SIZE, y * CHUNK_SIZE, z * CHUNK_SIZE);
	}

	public Chunk(int _x, int _y, int _z) {
		
		this.x = _x;
		this.y = _y;
		this.z = _z;
		
		blocks = new Block[CHUNK_SIZE_CUBED];
		
		for (int i = 0; i < CHUNK_SIZE_CUBED; i++) {
			int z = i / CHUNK_SIZE_SQUARED;
			int ii = i - (z * CHUNK_SIZE_SQUARED);
			int y = ii / CHUNK_SIZE;
			int x = ii % CHUNK_SIZE;
			if (SimplexNoise.noise((x + this.x * CHUNK_SIZE) / 10f, (y + this.y * CHUNK_SIZE) / 10f, (z + this.z * CHUNK_SIZE) / 10f) > 0.1f) {
			blocks[i] = new Block(x, y, z);
			}
		}
	}
	
	

	/**
	 * iterates over each block in a chunk and updates its neighboring block's links based
	 * on their positions within the chunk.
	 */
	public void updateBlocks() {
		for (int i = 0; i < CHUNK_SIZE_CUBED; i++) {
			Block b = blocks[i];
				if (b != null) {
				int n_x = i - 1;
				int p_x = i + 1;
				int n_y = i - CHUNK_SIZE;
				int p_y = i + CHUNK_SIZE;
				int n_z = i - CHUNK_SIZE_SQUARED;
				int p_z = i + CHUNK_SIZE_SQUARED;
				
				if (b.x - 1 < 0) {
					//TODO: check neighbor chunk
					b.lt = false;
				} else {
					Block bl = blocks[n_x];
					if (bl == null)
						b.lt = true;
					else
						b.lt = false;
				}
				if (b.y - 1 < 0) {
					//TODO: check neighbor chunk
					b.bt = false;
				} else {
					Block bl = blocks[n_y];
					if (bl == null)
						b.bt = true;
					else
						b.bt = false;
				}
				if (b.z - 1 < 0) {
					//TODO: check neighbor chunk
					b.ft = false;
				} else {
					Block bl = blocks[n_z];
					if (bl == null)
						b.ft = true;
					else
						b.ft = false;
				}
				
				if (b.x + 1 >= CHUNK_SIZE) {
					//TODO: check neighbor chunk
					b.rt = false;
				} else {
					Block bl = blocks[p_x];
					if (bl == null)
						b.rt = true;
					else
						b.rt = false;
				}
				if (b.y + 1 >= CHUNK_SIZE) {
					//TODO: check neighbor chunk
					b.tp = false;
				} else {
					Block bl = blocks[p_y];
					if (bl == null)
						b.tp = true;
					else
						b.tp = false;
				}
				if (b.z + 1 >= CHUNK_SIZE) {
					//TODO: check neighbor chunk
					b.bk = false;
				} else {
					Block bl = blocks[p_z];
					if (bl == null)
						b.bk = true;
					else
						b.bk = false;
				}
			}
		}
	}
	
//	class Vertex3i {
//		
//		public int x, y, z; 
//		public float u, v;
//		
//		public Vertex3i(x, y, z, u, v) {
//			
//		}
//		
//	}
	
	private ArrayList<Float> vertices = new ArrayList<>();
	private ArrayList<Integer> indices = new ArrayList<>();
	private boolean to_gen_model;
	
	
	/**
	 * sets a flag indicating whether a model should be generated or not.
	 */
	public void toGenModel() { toGenModel(false); };
	
	/**
	 * generates a model from a set of vertices, indices, and blocks. It loops through
	 * each block and recursively calls itself to generate new vertices and indices based
	 * on the chunk size. The function also implements filtering and re-indexing for
	 * textured cubes, but does not support it for now.
	 * 
	 * @param now state of the model generation, with `true` indicating that the model
	 * should be generated anew and `false` indicating that it should be reused from
	 * previous calls to the function.
	 */
	public void toGenModel(boolean now) {

		int max_index = 0;
//		System.out.println("gen model");
		for (int i = 0; i < CHUNK_SIZE_CUBED; i++) {
			Block b = blocks[i];
			if (b != null) {
				max_index = gen(vertices, indices, b, max_index);
					
			}
		}
//		System.out.println("vertice   : " + vertices.size() / 5 + " -- floats : " + vertices.size());
//		System.out.println("indices   : " + indices.size());
//		System.out.println("triangles : " + indices.size() / 3);
//		System.out.println("quads     : " + indices.size() / 6);
//		System.out.println("---------------------------\nloading model arrays");
		
		// cant implement filtering and re-indexing for textured cubes
//		{
//			
//			ArrayList<Integer>
//			
//		}
		
//		return Model.load(Util.toFloatArray(new_vertices), Util.toIntArray(new_indices));
		
		if (now) {
			createModel();
			to_gen_model = false;
		} else {
			to_gen_model = true;
		}
		
	}
	
	/**
	 * loads a 3D model from a buffer and stores it in a instance variable called `model`.
	 */
	private void createModel() {
		this.model = Model.load(Util.toFloatArray(vertices), Util.toIntArray(indices));
	}
	
	/**
	 * generates a new instance of the `Model` class based on input parameters and returns
	 * it.
	 * 
	 * @returns a `Model` object containing the generated model.
	 * 
	 * The `model` object is a `Model` instance that represents the generated model.
	 * The `toGenModel` method call within the `genModel` function sets the `model` field
	 * to the result of calling the `toGenModel` method with the `true` parameter,
	 * indicating that the model should be generated.
	 * Therefore, the `model` object returned by the `genModel` function has been generated
	 * and is ready for use.
	 */
	public Model genModel() {
		
		toGenModel(true);
		
		return this.model;
	}

	/**
	 * generates and adds vertices, indices to a list for a given block, based on its
	 * type (ft, bk, bt, tp, lt, rt) and maximum index value.
	 * 
	 * @param vertices 3D vertices of a cube or other polyhedron being generated, and it
	 * is used to add new vertices to the list as the block is processed.
	 * 
	 * 1/ The `List<Float>` `vertices` represents an array of floating-point numbers,
	 * which are used to construct the vertices of a 3D object in a mesh.
	 * 2/ Each element in the list is a single floating-point number, which corresponds
	 * to a specific point in the mesh.
	 * 3/ The size of the list is dynamic and can vary depending on the number of vertices
	 * generated by the block.
	 * 4/ The elements in the list are not necessarily distinct or unique, as they may
	 * be repeated for each face of a given block.
	 * 5/ There is no explicit indication of the data type of the elements in `vertices`,
	 * but based on the context, it can be inferred that they are floating-point numbers.
	 * 6/ The list is deserialized from a serialized format, likely produced by a previous
	 * `serialize` function call.
	 * 
	 * @param indices 3D indices of vertices in the mesh, which are used to keep track
	 * of the vertices that need to be generated for each block.
	 * 
	 * 	- `new int[] {0, 1, 2, 0, 2, 3}`: This is an array of integers that represent the
	 * positions of the vertices in the mesh. Each index in the array corresponds to a
	 * vertex in the mesh.
	 * 	- `max_index`: A variable that keeps track of the maximum index of the vertices
	 * in the mesh. It is used to calculate the indices of the vertices in the output
	 * arrays `vertices` and `indices`.
	 * 
	 * @param block 3D block to be rendered, and it is used to determine which vertices
	 * and indices to add to the `vertices` and `indices` lists, respectively.
	 * 
	 * 	- `x`, `y`, and `z`: These are the coordinates of the block in 3D space.
	 * 	- `ft`, `bk`, `bt`, `tp`, and `lt`: These are the various properties or attributes
	 * of the block, which determine how it should be rendered as a mesh:
	 * 	+ `ft`: If true, the block has a face at (x, y, z) that is not part of any larger
	 * face.
	 * 	+ `bk`: If true, the block has a back face at (x, y, z+1) that is not part of any
	 * larger face.
	 * 	+ `bt`: If true, the block has a top face at (x, y+1, z) that is not part of any
	 * larger face.
	 * 	+ `tp`: If true, the block has a top plane at (x, y+1, z) that is not part of any
	 * larger face.
	 * 	+ `lt`: If true, the block has a left top face at (x+1, y, z) that is not part
	 * of any larger face.
	 * 
	 * The `gen` function then serializes these properties into the mesh data structure
	 * by adding corresponding vertices and indices to the `vertices` and `indices` lists,
	 * respectively. The function returns the maximum index of the vertices in the mesh.
	 * 
	 * @param max_index 3D vertex index counter that is incremented for each new vertex
	 * added to the `vertices` list and `indices` list during the generation of the 3D mesh.
	 * 
	 * @returns an integer value representing the next maximum index for a given block
	 * and its vertices.
	 */
	private static int gen(List<Float> vertices, List<Integer> indices, Block block, int max_index) {
		
		float x = block.x;
		float y = block.y;
		float z = block.z;
		
		if (block.ft) {
			float[] tmp_v = { //
				x,   y,   z,   0, 0, //
				x+1, y,   z,   1, 0, //
				x+1, y+1, z,   1, 1, //
				x,   y+1, z,   0, 1, //
			}; //
			for (float f : tmp_v) vertices.add(f);
			for (int i : new int[] {0, 1, 2, 0, 2, 3}) indices.add(max_index + i);
			max_index += 4;
		}
		if (block.bk) {
			float[] tmp_v = { //
				x,   y,   z+1,   1, 0, //
				x+1, y,   z+1,   0, 0, //
				x+1, y+1, z+1,   0, 1, //
				x,   y+1, z+1,   1, 1, //
			}; //
			for (float f : tmp_v) vertices.add(f);
			for (int i : new int[] {0, 3, 2, 0, 2, 1}) indices.add(max_index + i);
			max_index += 4;
		}
		if (block.bt) {
			float[] tmp_v = { //
				x,   y,   z,     0, 0, //
				x+1, y,   z,   	 1, 0, //
				x+1, y,   z+1,   1, 1, //
				x,   y,   z+1,   0, 1, //
			}; //
			for (float f : tmp_v) vertices.add(f);
			for (int i : new int[] {0, 3, 2, 0, 2, 1}) indices.add(max_index + i);
			max_index += 4;
		}
		if (block.tp) {
			float[] tmp_v = { //
				x,   y+1, z,     0, 0, //
				x+1, y+1, z,     1, 0, //
				x+1, y+1, z+1,   1, 1, //
				x,   y+1, z+1,   0, 1, //
			}; //
			for (float f : tmp_v) vertices.add(f);
			for (int i : new int[] {0, 1, 2, 0, 2, 3}) indices.add(max_index + i);
			max_index += 4;
		}
		if (block.lt) {
			float[] tmp_v = { //
				x,   y,   z,     1, 0, //
				x,   y+1, z,     1, 1, //
				x,   y+1, z+1,   0, 1, //
				x,   y,   z+1,   0, 0, //
			}; //
			for (float f : tmp_v) vertices.add(f);
			for (int i : new int[] {0, 1, 2, 0, 2, 3}) indices.add(max_index + i);
			max_index += 4;
		}
		if (block.rt) {
			float[] tmp_v = { //
				x+1, y,   z,     0, 0, //
				x+1, y+1, z,     0, 1, //
				x+1, y+1, z+1,   1, 1, //
				x+1, y,   z+1,   1, 0, //
			}; //
			for (float f : tmp_v) vertices.add(f);
			for (int i : new int[] {0, 3, 2, 0, 2, 1}) indices.add(max_index + i);
			max_index += 4;
		}
		return max_index;
	}

}
