package com.ch;

import com.ch.math.Matrix4f;
import com.ch.math.Vector3f;

/**
 * is an abstract class that represents a camera in a 3D space. It has several fields
 * and methods for calculating and manipulating matrices related to the camera's
 * position, rotation, and projection. The class also has an abstract method for
 * calculating the camera's projection matrix and another method for adjusting the
 * camera to fit within a specified viewport.
 */
public abstract class Camera {

	protected Matrix4f projection;
	protected Matrix4f viewProjectionMat4;
	protected CameraStruct values;
	protected Transform transform;

	protected Camera(Matrix4f projection) {
		this.projection = projection;
		transform = new Transform();
	}

	/**
	 * computes and returns a `Matrix4f` object representing the view projection
	 * transformation, which combines the camera's view matrix and projection matrix. If
	 * the `viewProjectionMat4` is null or the transform has changed, it recalculates the
	 * view matrix.
	 * 
	 * @returns a `Matrix4f` object representing the view projection matrix.
	 * 
	 * 	- `viewProjectionMat4`: This is a matrix object representing the view projection
	 * transformation. It contains the view and projection matrices combined into a single
	 * 4x4 matrix.
	 * 	- `transform`: This is an instance of the `Transform` class, which stores the
	 * transformation information used to calculate the view matrix. The `hasChanged()`
	 * method is used to check if the transformation has changed since the last calculation.
	 * 
	 * In summary, the `getViewProjection` function returns a 4x4 matrix object representing
	 * the view projection transformation, which is calculated based on the current
	 * transformation state.
	 */
	public Matrix4f getViewProjection() {

		if (viewProjectionMat4 == null || transform.hasChanged()) {
			calculateViewMatrix();
		}

		return viewProjectionMat4;
	}

	/**
	 * calculates a view matrix that combines a camera's rotation and translation with
	 * the projection matrix to produce the final view matrix for rendering.
	 * 
	 * @returns a matrix that represents the view transformation of a camera, combining
	 * rotation and translation components.
	 * 
	 * 	- The output is a 4x4 matrix, representing the view matrix.
	 * 	- The first three columns represent the rotation of the camera relative to the
	 * world coordinate system, while the fourth column represents the translation of the
	 * camera relative to the origin of the world coordinate system.
	 * 	- The matrix is generated by multiplying the projection matrix with the rotation
	 * matrix and then with the translation matrix.
	 * 
	 * In summary, the `calculateViewMatrix` function returns a view matrix that takes
	 * into account both the rotation and translation of the camera, allowing for accurate
	 * rendering of 3D scenes from different viewpoints.
	 */
	public Matrix4f calculateViewMatrix() {

		Matrix4f cameraRotation = transform.getTransformedRot().conjugate().toRotationMatrix();
		Matrix4f cameraTranslation = getTranslationMatrix();

		return (viewProjectionMat4 = projection.mul(cameraRotation.mul(cameraTranslation)));

	}

	/**
	 * generates a 4x4 transformation matrix representing the negative translation of the
	 * camera position.
	 * 
	 * @returns a 4x4 transformation matrix representing the translation of the camera position.
	 * 
	 * The function returns a 4x4 matrix representing a translation in 3D space. The
	 * upper-left 3x3 submatrix represents the translation vector in world coordinates.
	 * 
	 * The lower-right 1x3 submatrix contains the components of the translation vector
	 * along the X, Y, and Z axes, respectively. These values represent the offset from
	 * the origin in each dimension.
	 * 
	 * In summary, the `getTranslationMatrix` function generates a matrix that represents
	 * a translation in 3D space, with the upper-left submatrix containing the translation
	 * vector in world coordinates and the lower-right submatrix containing the components
	 * of the translation vector along the X, Y, and Z axes.
	 */
	public Matrix4f getTranslationMatrix() {
		Vector3f cameraPos = transform.getTransformedPos().mul(-1);
		return new Matrix4f().initTranslation(cameraPos.getX(), cameraPos.getY(), cameraPos.getZ());
	}

	/**
	 * returns the `transform` object, which represents a transformation of some kind.
	 * 
	 * @returns a `Transform` object representing the transformation of the input data.
	 * 
	 * The `transform` variable is an object of the `Transform` class, which represents
	 * a transformation matrix in 3D space. It has several attributes, including the
	 * translation vector (x, y, z), rotation angle around each axis (x, y, z), and scaling
	 * factors for x, y, and z. These attributes can be used to perform various transformations
	 * on 3D objects, such as translating, rotating, or scaling them.
	 */
	public Transform getTransform() {
		return transform;
	}
	
	public abstract Matrix4f calculateProjectionMatrix(CameraStruct data);

	public abstract void adjustToViewport(int width, int height);

	/**
	 * is an abstract class that serves as a base for other camera classes in the file.
	 * It provides an abstract method called `getAsMatrix4()` which returns a Matrix4f
	 * object, but does not define any fields or methods of its own.
	 */
	protected abstract class CameraStruct {

		protected abstract Matrix4f getAsMatrix4();

	}

}
