package com.ch;

import org.lwjgl.opengl.GL11;
import org.lwjgl.opengl.GL15;
import org.lwjgl.opengl.GL20;
import org.lwjgl.opengl.GL30;

/**
 * is used to handle vertex and index buffer data for rendering 3D models in OpenGL.
 * It provides methods for binding and unbinding Vertex Array Objects (VAOs) and
 * Element Array Buffers (EABs), as well as storing vertex and index data and
 * enabling/disabling vertex attributtes. The class also provides a way to load
 * pre-defined model data from an array of vertices and indices.
 */
public class Model {

	private int vao, size;
	
	public Model(int vao, int count) {
		this.vao = vao;
		this.size = count;
	}
	
	/**
	 * binds a vertex array object, enables vertex attributes for position and texture
	 * coord, draws triangles using `glDrawElements`, disables vertex attributes, and
	 * unbinds the vertex array object.
	 */
	public void draw() {
		GL30.glBindVertexArray(vao);
		GL20.glEnableVertexAttribArray(0);
		GL20.glEnableVertexAttribArray(1);
		//GL11.glDrawArrays(GL11.GL_TRIANGLES, 0, size);
		GL11.glDrawElements(GL11.GL_TRIANGLES, size, GL11.GL_UNSIGNED_INT, 0);
		GL20.glDisableVertexAttribArray(0);
		GL20.glDisableVertexAttribArray(1);
		GL30.glBindVertexArray(0);
	}
	
	/**
	 * enables two vertex attributes in a GL context using `glEnableVertexAttribArray`.
	 */
	public static void enableAttribs() {
		GL20.glEnableVertexAttribArray(0);
		GL20.glEnableVertexAttribArray(1);
	}
	
	/**
	 * disables both vertex attribute arrays for a specific GL context.
	 */
	public static void disableAttribs() {
		GL20.glDisableVertexAttribArray(0);
		GL20.glDisableVertexAttribArray(1);
	}
	
	/**
	 * returns the value of the variable `vao`.
	 * 
	 * @returns an integer value representing the VAO.
	 */
	public int getVAO() {
		return vao;
	}
	
	/**
	 * retrieves the value of a field named `size`.
	 * 
	 * @returns the value of the `size` field.
	 */
	public int getSize() {
		return size;
	}
	
	/**
	 * loads a 3D model from an array of vertices and an array of indices. It creates a
	 * Vertex Array Object (VAO), stores the indices, and then binds and unbinds the VAO.
	 * Finally, it returns a `Model` object representing the loaded model.
	 * 
	 * @param vertices 3D geometric data of the model to be loaded, which is stored in
	 * an array of floating-point values.
	 * 
	 * 	- `vertices`: An array of floating-point values representing the 3D vertices of
	 * a model.
	 * 	- `indices`: An array of integers representing the indices of the vertices in the
	 * model.
	 * 
	 * @param indices 3D model's vertex indices, which are used to bind the vertices of
	 * the model to its corresponding geometry in the graphics pipeline.
	 * 
	 * 	- `indices`: An `int[]` array containing the indices of the vertices in the model.
	 * 	- `v_count`: The number of vertices in the model, which can be calculated by
	 * summing up the lengths of all the `indices` arrays.
	 * 
	 * @returns a `Model` object representing the loaded 3D model.
	 * 
	 * 	- `Model`: This is the type of the output, which is an instance of the `Model` class.
	 * 	- `vao`: This is an integer variable representing the VAO (Vertex Array Object)
	 * handle created by the function.
	 * 	- `v_count`: This is an integer variable representing the number of vertices in
	 * the model.
	 */
	public static Model load(float[] vertices, int[] indices) {
		int vao = createVAO();
		storeIndices(indices);
		storeData(0, vertices);
		unbindVAO();
		int v_count = indices.length;
		return new Model(vao, v_count);
	}
	
	/**
	 * generates a new vertex array object (Vao) and binds it to the current context,
	 * allowing for its use in rendering graphics.
	 * 
	 * @returns an integer value representing the unique vertex array object (VAO) created.
	 */
	private static int createVAO() {
		int vao = GL30.glGenVertexArrays();
		GL30.glBindVertexArray(vao);
		return vao;
	}
	
	/**
	 * stores floating-point array data into a buffer object and sets vertex attributes
	 * for rendering.
	 * 
	 * @param attrib 3D vertex attribute index that stores the data for the current buffer
	 * in the GPU's memory.
	 * 
	 * @param data 2D array of floating-point values that will be stored in the vertex
	 * buffer object (VBO).
	 * 
	 * 	- `data`: An array of 4 float values representing vertex data.
	 * 	- `attrib`: An integer representing the attribute index to which the vertex data
	 * will be mapped. There are two attribute indices in total, assigned using the
	 * `GL20.glVertexAttribPointer()` method.
	 * 	- `vbo`: A buffer object handle generated by `GL15.glGenBuffers()`. The buffer
	 * is bound using `GL15.glBindBuffer(GL15.GL_ARRAY_BUFFER, vbo)` and data is transferred
	 * to it using `GL15.glBufferData(GL15.GL_ARRAY_BUFFER, Util.createFlippedBuffer(data),
	 * GL15.GL_STATIC_DRAW)`.
	 */
	private static void storeData(int attrib, float[] data) {
		int vbo = GL15.glGenBuffers();
		GL15.glBindBuffer(GL15.GL_ARRAY_BUFFER, vbo);
		GL15.glBufferData(GL15.GL_ARRAY_BUFFER, Util.createFlippedBuffer(data), GL15.GL_STATIC_DRAW);
		GL20.glVertexAttribPointer(attrib, 3, GL11.GL_FLOAT, false, 5 * 4,     0);
		GL20.glVertexAttribPointer(attrib + 1, 2, GL11.GL_FLOAT, false, 5 * 4, 3 * 4);
		GL15.glBindBuffer(GL15.GL_ARRAY_BUFFER, 0);
	}
	
	/**
	 * genrates a new buffer object and binds it to an element array buffer, then stores
	 * the provided integer array data in the buffer using the `glBufferData` method.
	 * 
	 * @param indices 3D indices of the vertices of a geometric shape, which are stored
	 * in a buffer for later use in rendering.
	 * 
	 * 	- `indices` is an integer array representing a buffer containing indices for an
	 * element array buffer.
	 * 	- The length of the array is specified by the size of the `indices` array, which
	 * is a variable passed as a parameter to the function.
	 * 	- Each element in the `indices` array represents an index into a buffer for an
	 * element array, with each index being an integer value between 0 and the total
	 * number of elements in the buffer - 1, inclusive.
	 */
	private static void storeIndices(int[] indices) {
		int ibo = GL15.glGenBuffers();
		GL15.glBindBuffer(GL15.GL_ELEMENT_ARRAY_BUFFER, ibo);
		GL15.glBufferData(GL15.GL_ELEMENT_ARRAY_BUFFER, Util.createFlippedBuffer(indices), GL15.GL_STATIC_DRAW);
	}
	
	/**
	 * binds a vertex array object (VAO) using the `GL30.glBindVertexArray()` method,
	 * setting it to null.
	 */
	private static void unbindVAO() {
		GL30.glBindVertexArray(0);
	}
	
}
