package com.ch;

import org.lwjgl.opengl.GL11;
import org.lwjgl.opengl.GL15;
import org.lwjgl.opengl.GL20;
import org.lwjgl.opengl.GL30;

public class Model {

	private int vao, size;
	
	public Model(int vao, int count) {
		this.vao = vao;
		this.size = count;
	}
	
	/**
	 * This function prepares and draws a 2D triangle mesh using OpenGL. It binds a vertex
	 * array object (Vao), enables vertex attribute arrays for vertices position and color
	 * elements and then draws the triangles using glDrawElements. Finally it disables
	 * the attribute arrays and unbinds the Vao.
	 */
	public void draw() {
		GL30.glBindVertexArray(vao);
		GL20.glEnableVertexAttribArray(0);
		GL20.glEnableVertexAttribArray(1);
		//GL11.glDrawArrays(GL11.GL_TRIANGLES, 0, size);
		GL11.glDrawElements(GL11.GL_TRIANGLES, size, GL11.GL_UNSIGNED_INT, 0);
		GL20.glDisableVertexAttribArray(0);
		GL20.glDisableVertexAttribArray(1);
		GL30.glBindVertexArray(0);
	}
	
	/**
	 * This function enables two vertex attribute arrays using `GL20.glEnableVertexAttribArray()`.
	 */
	public static void enableAttribs() {
		GL20.glEnableVertexAttribArray(0);
		GL20.glEnableVertexAttribArray(1);
	}
	
	/**
	 * This function disables two vertex attrib arrays: one at index 0 and another at
	 * index 1.
	 */
	public static void disableAttribs() {
		GL20.glDisableVertexAttribArray(0);
		GL20.glDisableVertexAttribArray(1);
	}
	
	/**
	 * This function returns the value of the "vao" field.
	 * 
	 * @returns The output returned by this function is `null`. The function is attempting
	 * to return the value of the field `vao`, but since `vao` is not initialized or
	 * defined anywhere before it is used as a return value., it is effectively `undefined`.
	 */
	public int getVAO() {
		return vao;
	}
	
	/**
	 * This function returns the value of the "size" field of the object.
	 * 
	 * @returns The output returned by this function is `undefined`.
	 */
	public int getSize() {
		return size;
	}
	
	/**
	 * This function creates a VaO (Vertex Array Object) from a float array of vertices
	 * and an int array of indices and returns a new Model object with the loaded data.
	 * 
	 * @param vertices The `vertices` input parameter is an array of floating-point numbers
	 * that contains the vertex positions for the 3D model. It is passed to the `storeData`
	 * method to set the vertex attributes for the VAO (Value Assembly Object).
	 * 
	 * @param indices The `indices` parameter is an array of integers that defines the
	 * vertex order for the generated mesh. It specifies which vertices belong together
	 * and how they should be drawn.
	 * 
	 * @returns The function `load` returns a `Model` object containing a `VAO` (Vertex
	 * Array Object) and the number of vertices (`v_count`).
	 */
	public static Model load(float[] vertices, int[] indices) {
		int vao = createVAO();
		storeIndices(indices);
		storeData(0, vertices);
		unbindVAO();
		int v_count = indices.length;
		return new Model(vao, v_count);
	}
	
	/**
	 * This function creates a vertex array object (VAO) and returns its identifier.
	 * 
	 * @returns The output of this function is an integer `vao` that represents a Vertex
	 * Array Object (VAO) generated using the `glGenVertexArrays()` function. The
	 * `GL30.glBindVertexArray(vao)` command binds the VAO to the currently active OpenGL
	 * context. In other words: the function creates and returns an ID for a newly generated
	 * VAO.
	 */
	private static int createVAO() {
		int vao = GL30.glGenVertexArrays();
		GL30.glBindVertexArray(vao);
		return vao;
	}
	
	/**
	 * This function stores 3D position and color data into an OpenGL buffer object (VBO).
	 * It uses the `glVertexAttribPointer()` method to configure the buffer as a vertex
	 * attribute pointer for the shader program.
	 * 
	 * @param attrib The `attrib` input parameter specifies the vertex attribute that the
	 * function should set up for the stored data.
	 * 
	 * @param data The `data` input parameter is an array of float values that are used
	 * to fill the VBO (Vertex Buffer Object) generated by the function.
	 */
	private static void storeData(int attrib, float[] data) {
		int vbo = GL15.glGenBuffers();
		GL15.glBindBuffer(GL15.GL_ARRAY_BUFFER, vbo);
		GL15.glBufferData(GL15.GL_ARRAY_BUFFER, Util.createFlippedBuffer(data), GL15.GL_STATIC_DRAW);
		GL20.glVertexAttribPointer(attrib, 3, GL11.GL_FLOAT, false, 5 * 4,     0);
		GL20.glVertexAttribPointer(attrib + 1, 2, GL11.GL_FLOAT, false, 5 * 4, 3 * 4);
		GL15.glBindBuffer(GL15.GL_ARRAY_BUFFER, 0);
	}
	
	/**
	 * This function stores the given array of integers (indices) into a buffer object
	 * using OpenGL's element array buffer.
	 * 
	 * @param indices The `indices` parameter is an array of integer values that represents
	 * the indices of the elements to be stored into the element array buffer.
	 */
	private static void storeIndices(int[] indices) {
		int ibo = GL15.glGenBuffers();
		GL15.glBindBuffer(GL15.GL_ELEMENT_ARRAY_BUFFER, ibo);
		GL15.glBufferData(GL15.GL_ELEMENT_ARRAY_BUFFER, Util.createFlippedBuffer(indices), GL15.GL_STATIC_DRAW);
	}
	
	/**
	 * This function sets the OpenGL Vertex Array Object (VAO) to zero (i.e., unbinds it).
	 */
	private static void unbindVAO() {
		GL30.glBindVertexArray(0);
	}
	
}

