package com.ch;

import static org.lwjgl.opengl.GL20.GL_COMPILE_STATUS;
import static org.lwjgl.opengl.GL20.GL_LINK_STATUS;
import static org.lwjgl.opengl.GL20.GL_VALIDATE_STATUS;
import static org.lwjgl.opengl.GL20.glGetProgramInfoLog;
import static org.lwjgl.opengl.GL20.glGetProgrami;
import static org.lwjgl.opengl.GL20.glGetShaderInfoLog;
import static org.lwjgl.opengl.GL20.glGetShaderi;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

import org.lwjgl.opengl.GL20;

import com.ch.math.Matrix4f;

/**
 * from the file provides a framework for creating and managing shaders in OpenGL.
 * It allows for uniform and matrix operations, as well as validation of the program.
 * The class provides methods for binding the program, getting the location of uniforms
 * and matrices, and loading shaders.
 */
public class Shader {
	
	private int program;
	
	public Shader(int program) {
		this.program = program;
	}
	
	/**
	 * glues a program to a specific OpenGL context, enabling its use for rendering.
	 */
	public void bind() {
		GL20.glUseProgram(program);
	}
	
	/**
	 * returns the value of the `program` field of an object.
	 * 
	 * @returns the value of the `program` field.
	 */
	public int getProgram() {
		return this.program;
	}
	
	/**
	 * is a utility method that sets a uniform float value for a specified location in a
	 * GL context, based on the length of the input array of values.
	 * 
	 * @param name name of the uniform location being set.
	 */
	public void uniformf(String name, float ...vals) {
		switch (vals.length) {
		case 1:
			GL20.glUniform1f(getLoaction(name), vals[0]);
			break;
		case 2:
			GL20.glUniform2f(getLoaction(name), vals[0], vals[1]);
			break;
		case 3:
			GL20.glUniform3f(getLoaction(name), vals[0], vals[1], vals[2]);
			break;
		case 4:
			GL20.glUniform4f(getLoaction(name), vals[0], vals[1], vals[2], vals[3]);
			break;
		}
	}
	
	/**
	 * sets a 4x4 matrix as a uniform variable in the current GL context using the
	 * `glUniformMatrix4` method. The matrix data is provided by the `mat` parameter and
	 * is stored in a flipped buffer for efficient access on some GPUs.
	 * 
	 * @param name 0-based index of a uniform buffer object for which the matrix is being
	 * set.
	 * 
	 * @param mat 4x4 floating-point matrix to be uniformed.
	 * 
	 * 	- `name`: A string parameter representing the uniform name.
	 * 	- `mat`: An instance of `Matrix4f`, which is a matrix with 16 double-precision
	 * floating-point elements representing the 4x4 homogeneous transformation matrix.
	 * 	- `getLocation(name)`: Returns an integer indicating the location in the shader
	 * where the uniform should be stored.
	 * 	- `false`: A boolean parameter indicating whether the uniform should be passed
	 * as a 32-bit floating-point value or as a binary buffer.
	 */
	public void unifromMat4(String name, Matrix4f mat) {
		GL20.glUniformMatrix4(getLoaction(name), false, Util.createFlippedBuffer(mat.getLinearData()));
	}
	
	/**
	 * returns the location of a uniform in a program using the `GL20` class.
	 * 
	 * @param name name of the uniform location to retrieve in the OpenGL program.
	 * 
	 * @returns an integer representing the location of a uniform in a GPU program.
	 */
	public int getLoaction(String name) {
		return GL20.glGetUniformLocation(program, name);
	}
	
	private static final String VERT = ".vert", FRAG = ".frag";
	
	/**
	 * loads a shader program from a file, consisting of a vertex and fragment shader,
	 * validates the program, and returns a new Shader object representing the loaded program.
	 * 
	 * @param filename name of the file containing the vertex and fragment shaders to be
	 * loaded into the program.
	 * 
	 * @returns a `Shader` object representing the compiled shader program.
	 * 
	 * 	- The output is a new `Shader` object, which represents a shader program created
	 * by combining a vertex shader and a fragment shader using the `GL20.glCreateProgram()`
	 * method.
	 * 	- The `Shader` object has a single field, `program`, which contains the program
	 * ID generated by `GL20.glCreateProgram()`. This ID can be used to activate and query
	 * the shader program using `GL20.glUseProgram()` and `GL20.glGetProgramiv()`.
	 * 	- The `Shader` object does not store any information about the vertex or fragment
	 * shaders themselves, such as their source code or metadata. Instead, it only contains
	 * a reference to the program ID generated by `loadShader()`.
	 * 
	 * Therefore, the `loadShader` function returns a `Shader` object that represents a
	 * new shader program, but does not provide any information about the individual
	 * vertex and fragment shaders that were used to create it.
	 */
	public static Shader loadShader(String filename) {
		int program = GL20.glCreateProgram();
		loadShader(GL20.GL_VERTEX_SHADER, getText(filename + VERT), program);
		loadShader(GL20.GL_FRAGMENT_SHADER, getText(filename + FRAG), program);
		validateProgram(program);
		return new Shader(program);
	}
	
	/**
	 * loads a shader program into memory by creating and compiling a new shader or
	 * attaching an existing one to a program, depending on the target platform.
	 * 
	 * @param target type of shader being created, which can be either a vertex shader
	 * or a fragment shader.
	 * 
	 * @param src source code of the shader to be compiled.
	 * 
	 * @param program 3D graphics program that the shader will be attached to after being
	 * compiled.
	 */
	private static void loadShader(int target, String src, int program) {
		int shader = GL20.glCreateShader(target);
		
		GL20.glShaderSource(shader, src);
		GL20.glCompileShader(shader);
		
		if (glGetShaderi(shader, GL_COMPILE_STATUS) == 0) {
			System.err.println(glGetShaderInfoLog(shader, 1024));
			System.exit(1);
		}
		
		GL20.glAttachShader(program, shader);
	}
	
	/**
	 * validates a program's linking and validation status using GL20 functions, printing
	 * any error messages to `System.err` and exiting with an error code if necessary.
	 * 
	 * @param program 3D graphics program to be validated, and it is passed to the
	 * `glLinkProgram`, `glValidateProgram`, and `glGetProgramInfoLog` functions for
	 * validation and error checking.
	 */
	private static void validateProgram(int program) {
		GL20.glLinkProgram(program);
		
		if (glGetProgrami(program, GL_LINK_STATUS) == 0) {
			System.err.println(glGetProgramInfoLog(program, 1024));
			System.exit(1);
		}
		
		GL20.glValidateProgram(program);
		
		if (glGetProgrami(program, GL_VALIDATE_STATUS) == 0) {
			System.err.println(glGetProgramInfoLog(program, 1024));
			System.exit(1);
		}
	}
	
	/**
	 * reads the contents of a specified file and returns the read text as a string.
	 * 
	 * @param file path to a file from which the text is read.
	 * 
	 * @returns a string representation of the contents of the specified file.
	 */
	private static String getText(String file) {
		String text = "";
		try {
			InputStream is = new FileInputStream(file);
			int ch;
			while ((ch = is.read()) != -1)
				text += (char) ch;
			is.close();
		} catch (IOException e) {
			e.printStackTrace();
			System.exit(1);
		}
		return text;
	}

}
