package com.ch;

import static org.lwjgl.opengl.GL20.GL_COMPILE_STATUS;
import static org.lwjgl.opengl.GL20.GL_LINK_STATUS;
import static org.lwjgl.opengl.GL20.GL_VALIDATE_STATUS;
import static org.lwjgl.opengl.GL20.glGetProgramInfoLog;
import static org.lwjgl.opengl.GL20.glGetProgrami;
import static org.lwjgl.opengl.GL20.glGetShaderInfoLog;
import static org.lwjgl.opengl.GL20.glGetShaderi;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

import org.lwjgl.opengl.GL20;

import com.ch.math.Matrix4f;

/**
 * in Java provides functionality for binding a program to a specific context, uniform
 * floating-point values, and matrix transformations. The class also includes methods
 * for loading shaders from files and validating the program after linking it.
 */
public class Shader {
	
	private int program;
	
	public Shader(int program) {
		this.program = program;
	}
	
	/**
	 * glUseProgram(program) and sets the current program to be used for rendering.
	 */
	public void bind() {
		GL20.glUseProgram(program);
	}
	
	/**
	 * retrieves the value of a field called `program`.
	 * 
	 * @returns an integer value representing the program.
	 */
	public int getProgram() {
		return this.program;
	}
	
	/**
	 * in Java is a method that sets uniform float values for a given location in an
	 * OpenGL context. It takes a name and an array of float values as input, and uses
	 * the `glUniformf` function to set the corresponding values in the context. The
	 * function handles different lengths of arrays (1-4 floats) and switches between the
	 * appropriate `glUniformf` calls accordingly.
	 * 
	 * @param name location of the uniform in the shader program, and is used to specify
	 * the correct glUniform* function to call for each length of vector input.
	 */
	public void uniformf(String name, float ...vals) {
		switch (vals.length) {
		case 1:
			GL20.glUniform1f(getLoaction(name), vals[0]);
			break;
		case 2:
			GL20.glUniform2f(getLoaction(name), vals[0], vals[1]);
			break;
		case 3:
			GL20.glUniform3f(getLoaction(name), vals[0], vals[1], vals[2]);
			break;
		case 4:
			GL20.glUniform4f(getLoaction(name), vals[0], vals[1], vals[2], vals[3]);
			break;
		}
	}
	
	/**
	 * sets a matrix as a uniform buffer in OpenGL using the `glUniformMatrix4` method.
	 * The matrix data is obtained from the `mat` parameter and stored in an flipped
	 * buffer for efficient access.
	 * 
	 * @param name 0-based index of the uniform location where the matrix should be stored.
	 * 
	 * @param mat 4x4 matrix to be uniformed and is passed to the `glUniformMatrix4()` method.
	 * 
	 * 	- The method takes a string parameter named `name`, which represents the location
	 * in the GPU where the uniform matrix will be stored.
	 * 	- The input `mat` is a `Matrix4f` object, representing a 4x4 homogeneous
	 * transformation matrix in floating-point format.
	 * 	- The `getLinearData()` method of the `Matrix4f` class returns a byte array
	 * containing the raw data of the matrix, which is then passed to the `glUniformMatrix4()`
	 * method to upload it to the GPU.
	 * 	- The `Util.createFlippedBuffer(mat.getLinearData())` method creates a new buffer
	 * object that stores the flipped version of the input matrix's data.
	 */
	public void unifromMat4(String name, Matrix4f mat) {
		GL20.glUniformMatrix4(getLoaction(name), false, Util.createFlippedBuffer(mat.getLinearData()));
	}
	
	/**
	 * retrieves the location of a uniform in a shader program specified by the `name`
	 * parameter using the `GL20.glGetUniformLocation` method.
	 * 
	 * @param name 0-based index of a uniform location in the program to retrieve.
	 * 
	 * @returns an integer representing the location of a uniform in a graphics program.
	 */
	public int getLoaction(String name) {
		return GL20.glGetUniformLocation(program, name);
	}
	
	private static final String VERT = ".vert", FRAG = ".frag";
	
	/**
	 * loads a shader program from a file and validates it, returning a new shader object.
	 * 
	 * @param filename name of the shader file to be loaded.
	 * 
	 * @returns a new `Shader` object that represents a shader program created by combining
	 * a vertex shader and a fragment shader.
	 * 
	 * 	- The function returns a new Shader object, which represents a shader program
	 * that can be used to render 3D graphics in a GPU.
	 * 	- The Shader object contains the program ID generated by GL20.glCreateProgram(),
	 * which is a unique identifier for the shader program.
	 * 	- The Shader object also stores the vertex and fragment shaders that were loaded
	 * into the program using loadShader(). These shaders are the individual parts of the
	 * shader program that define the graphics processing pipeline.
	 * 	- The Shader object provides methods for validating the shader program, which is
	 * important to ensure that the program is functioning correctly and producing the
	 * expected results.
	 */
	public static Shader loadShader(String filename) {
		int program = GL20.glCreateProgram();
		loadShader(GL20.GL_VERTEX_SHADER, getText(filename + VERT), program);
		loadShader(GL20.GL_FRAGMENT_SHADER, getText(filename + FRAG), program);
		validateProgram(program);
		return new Shader(program);
	}
	
	/**
	 * creates a new shader program and attaches it to the main program. It compiles the
	 * shader source code using GL20.glCompileShader() and handles any compilation errors
	 * by printing the error message to System.err and exiting the program.
	 * 
	 * @param target type of shader (either Vertex or Fragment) that the function is loading.
	 * 
	 * @param src source code of the shader to be compiled.
	 * 
	 * @param program 3D graphics program that the shader will be attached to after being
	 * compiled.
	 */
	private static void loadShader(int target, String src, int program) {
		int shader = GL20.glCreateShader(target);
		
		GL20.glShaderSource(shader, src);
		GL20.glCompileShader(shader);
		
		if (glGetShaderi(shader, GL_COMPILE_STATUS) == 0) {
			System.err.println(glGetShaderInfoLog(shader, 1024));
			System.exit(1);
		}
		
		GL20.glAttachShader(program, shader);
	}
	
	/**
	 * validates a program using the `glLinkProgram` and `glValidateProgram` methods,
	 * checking for errors and exiting the application if any are found.
	 * 
	 * @param program 3D program to be validated and linked with the OpenGL context.
	 */
	private static void validateProgram(int program) {
		GL20.glLinkProgram(program);
		
		if (glGetProgrami(program, GL_LINK_STATUS) == 0) {
			System.err.println(glGetProgramInfoLog(program, 1024));
			System.exit(1);
		}
		
		GL20.glValidateProgram(program);
		
		if (glGetProgrami(program, GL_VALIDATE_STATUS) == 0) {
			System.err.println(glGetProgramInfoLog(program, 1024));
			System.exit(1);
		}
	}
	
	/**
	 * reads the contents of a given file and returns its text as a string.
	 * 
	 * @param file name of a file that contains the text to be read.
	 * 
	 * @returns a string representation of the contents of the specified file.
	 */
	private static String getText(String file) {
		String text = "";
		try {
			InputStream is = new FileInputStream(file);
			int ch;
			while ((ch = is.read()) != -1)
				text += (char) ch;
			is.close();
		} catch (IOException e) {
			e.printStackTrace();
			System.exit(1);
		}
		return text;
	}

}
