package com.ch;

import static org.lwjgl.opengl.GL20.GL_COMPILE_STATUS;
import static org.lwjgl.opengl.GL20.GL_LINK_STATUS;
import static org.lwjgl.opengl.GL20.GL_VALIDATE_STATUS;
import static org.lwjgl.opengl.GL20.glGetProgramInfoLog;
import static org.lwjgl.opengl.GL20.glGetProgrami;
import static org.lwjgl.opengl.GL20.glGetShaderInfoLog;
import static org.lwjgl.opengl.GL20.glGetShaderi;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

import org.lwjgl.opengl.GL20;

import com.ch.math.Matrix4f;

/**
 * from the file provides a way to load and manage shaders for use in a graphics
 * program. It allows for the creation of a program object and uniform values can be
 * set for matrices and floats. Additionally, it provides a method to bind the program
 * and get the location of a specified uniform.
 */
public class Shader {
	
	private int program;
	
	public Shader(int program) {
		this.program = program;
	}
	
	/**
	 * glues a program to a specific context, allowing it to be used for rendering and
	 * other graphics operations.
	 */
	public void bind() {
		GL20.glUseProgram(program);
	}
	
	/**
	 * returns the value of the `program` field of the current instance.
	 * 
	 * @returns an integer representation of the program.
	 */
	public int getProgram() {
		return this.program;
	}
	
	/**
	 * is a method that takes a string name and an array of float values as parameters.
	 * It then uses the `glUniformf()` method to set the specified uniform value(s) for
	 * the named location in the current GL context. The length of the input array
	 * determines which `glUniformf()` method is called, with longer arrays being handled
	 * by more complex versions of the method.
	 * 
	 * @param name 0-based index of the uniform location in the program's graphics handling
	 * state, which determines where to write the corresponding uniform value(s) using
	 * GL20.glUniform() method calls.
	 */
	public void uniformf(String name, float ...vals) {
		switch (vals.length) {
		case 1:
			GL20.glUniform1f(getLoaction(name), vals[0]);
			break;
		case 2:
			GL20.glUniform2f(getLoaction(name), vals[0], vals[1]);
			break;
		case 3:
			GL20.glUniform3f(getLoaction(name), vals[0], vals[1], vals[2]);
			break;
		case 4:
			GL20.glUniform4f(getLoaction(name), vals[0], vals[1], vals[2], vals[3]);
			break;
		}
	}
	
	/**
	 * passes a matrix object to OpenGL using the `glUniformMatrix4` method, with the
	 * location index specified by the name parameter and the buffer flag set to false.
	 * 
	 * @param name 0-based index of a uniform buffer location where the provided matrix
	 * will be stored.
	 * 
	 * @param mat 4x4 floating-point matrix to be uniformed.
	 * 
	 * 	- `getLocation(name)` is used to retrieve the location object for the uniform
	 * named `name`. This location object provides the necessary information to bind the
	 * uniform to a shader program.
	 * 	- `glUniformMatrix4()` is used to set a 4x4 matrix as a uniform in a shader
	 * program. The matrix data is provided by `Util.createFlippedBuffer(mat.getLinearData())`,
	 * which creates a buffer object from the linear data of the `mat` matrix.
	 * 	- `false` is passed as the second argument to indicate that the uniform should
	 * be bound as a column-major matrix, rather than a row-major matrix.
	 */
	public void unifromMat4(String name, Matrix4f mat) {
		GL20.glUniformMatrix4(getLoaction(name), false, Util.createFlippedBuffer(mat.getLinearData()));
	}
	
	/**
	 * retrieves the location of a uniform named "name" within a program specified by the
	 * `program` parameter using the `GL20.glGetUniformLocation()` method.
	 * 
	 * @param name 0-based index of the uniform location to retrieve in the program's
	 * uniform buffer.
	 * 
	 * @returns an integer representing the uniform location within a program.
	 */
	public int getLoaction(String name) {
		return GL20.glGetUniformLocation(program, name);
	}
	
	private static final String VERT = ".vert", FRAG = ".frag";
	
	/**
	 * loads a shader from a file, creates a program object in OpenGL, and returns a new
	 * shader object containing the loaded shader.
	 * 
	 * @param filename path to a file containing the vertex and fragment shaders to be
	 * loaded into the program.
	 * 
	 * @returns a new `Shader` object representing a shader program created by combining
	 * a vertex shader and a fragment shader.
	 * 
	 * 	- The function returns a new Shader object, which represents a shader program
	 * that can be used for rendering 3D graphics.
	 * 	- The Shader object has a reference to the program ID generated by GL20.glCreateProgram(),
	 * which is used to identify the shader program.
	 * 	- The Shader object can be validated using the validateProgram() method, which
	 * checks if the shader program is properly linked and ready for use.
	 * 
	 * Overall, the `loadShader` function is responsible for loading and creating a shader
	 * program from a given filename, and returning it as a new Shader object that can
	 * be used for rendering purposes.
	 */
	public static Shader loadShader(String filename) {
		int program = GL20.glCreateProgram();
		loadShader(GL20.GL_VERTEX_SHADER, getText(filename + VERT), program);
		loadShader(GL20.GL_FRAGMENT_SHADER, getText(filename + FRAG), program);
		validateProgram(program);
		return new Shader(program);
	}
	
	/**
	 * creates a new shader object using the `glCreateShader()` method, then sets the
	 * source code for the shader using `glShaderSource()`, compiles the shader using
	 * `glCompileShader()`, and attaches the shader to a program using `glAttachShader()`.
	 * 
	 * @param target 3D graphics context's current active program, which is used to
	 * determine the type of shader to create and attach to the program.
	 * 
	 * @param src source code of the shader to be compiled.
	 * 
	 * @param program 3D graphics program to which the loaded shader will be attached.
	 */
	private static void loadShader(int target, String src, int program) {
		int shader = GL20.glCreateShader(target);
		
		GL20.glShaderSource(shader, src);
		GL20.glCompileShader(shader);
		
		if (glGetShaderi(shader, GL_COMPILE_STATUS) == 0) {
			System.err.println(glGetShaderInfoLog(shader, 1024));
			System.exit(1);
		}
		
		GL20.glAttachShader(program, shader);
	}
	
	/**
	 * validates a program by linking and validating it with the GPU, checking for errors
	 * and displaying any that occur.
	 * 
	 * @param program 3D program that needs to be validated, and it is passed through
	 * various gl* functions for linking and validation.
	 */
	private static void validateProgram(int program) {
		GL20.glLinkProgram(program);
		
		if (glGetProgrami(program, GL_LINK_STATUS) == 0) {
			System.err.println(glGetProgramInfoLog(program, 1024));
			System.exit(1);
		}
		
		GL20.glValidateProgram(program);
		
		if (glGetProgrami(program, GL_VALIDATE_STATUS) == 0) {
			System.err.println(glGetProgramInfoLog(program, 1024));
			System.exit(1);
		}
	}
	
	/**
	 * reads the contents of a file and returns its text as a string.
	 * 
	 * @param file file to read and contains its path.
	 * 
	 * @returns a string containing the contents of the specified file.
	 */
	private static String getText(String file) {
		String text = "";
		try {
			InputStream is = new FileInputStream(file);
			int ch;
			while ((ch = is.read()) != -1)
				text += (char) ch;
			is.close();
		} catch (IOException e) {
			e.printStackTrace();
			System.exit(1);
		}
		return text;
	}

}
